# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# IMPORTANTE: verifica estos numeros en https://fabricmc.net/develop antes de compilar,
# ya que las builds de yarn se actualizan con frecuencia y esta puede haber quedado vieja.
minecraft_version=1.19.2
yarn_mappings=1.19.2+build.28
loader_version=0.14.24
loom_version=1.4-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=ru.matt
archives_base_name=visualratio

# Dependencies
fabric_version=0.76.0+1.19.2
modmenu_version=4.1.2
